### ISSUE TITLE
`uninitialized constant Chroma::APIOperations::Data (NameError)`

### ISSUE THREAD

**Issue by andreibondarev** [mariochavez/chroma#8]
Error stack:

```
 -> langchain [main*]: irb
irb(main):001:0> require 'chroma-db'
/Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/chroma-db-0.2.0/lib/chroma/api_operations/request.rb:11:in `<module:APIOperations>': uninitialized constant Chroma::APIOperations::Data (NameError)

    Response = Data.define(:status, :body, :headers, :error)
               ^^^^
	from /Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/chroma-db-0.2.0/lib/chroma/api_operations/request.rb:4:in `<module:Chroma>'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/chroma-db-0.2.0/lib/chroma/api_operations/request.rb:3:in `<top (required)>'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/chroma-db-0.2.0/lib/chroma-db.rb:14:in `require_relative'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/chroma-db-0.2.0/lib/chroma-db.rb:14:in `<top (required)>'
	from <internal:/Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from (irb):1:in `<main>'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.6.4/exe/irb:9:in `<top (required)>'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/bin/irb:25:in `load'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/bin/irb:25:in `<main>'
<internal:/Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- chroma-db (LoadError)
	from <internal:/Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):1:in `<main>'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.6.4/exe/irb:9:in `<top (required)>'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/bin/irb:25:in `load'
	from /Users/andrei/.asdf/installs/ruby/3.1.2/bin/irb:25:in `<main>'
irb(main):002:0>
```

**Comment by andreibondarev** [comment]
@mariochavez Also -- would it be possible to relax the Ruby version requirement for those installing the gem with an earlier Ruby version? https://github.com/mariochavez/chroma/blob/main/chroma-db.gemspec#L15

I'd recommend going down to `">= 2.6.0"`

**Comment by mariochavez** [comment]
Hi!

The gem uses the newest Ruby syntax; it will not work with Ruby 3.1 or older. Needs 3.2 or better.
Changing the gem code to relax the Ruby version means a rewrite of this gem.

I'll try to add Ruby Next to polyfill the newest syntax to older Ruby, but I can't make any commitment that this will work.

Mario

**Comment by mariochavez** [comment]
I'm releasing a new version of this gem. It uses ruby-next to provide backward compatibility with older versions of ruby down to 2.7.8

https://github.com/mariochavez/chroma/pull/9

**Comment by andreibondarev** [comment]
Wow @mariochavez, incredible job! Thank you so much for knocking this out so quickly!

**Comment by mariochavez** [comment]
Closing this for now.

**Comment by andreibondarev** [comment]
@mariochavez I'm up and running! Thank you sir!

**Comment by andreibondarev** [comment]
@mariochavez It's integrated into langchain.rb now: https://github.com/andreibondarev/langchainrb/pull/20

**Comment by mariochavez** [comment]
@andreibondarev awesome!
